const PERFORMERS = {
    LOAD: 'PERFORMERS_LOAD',
    LOAD_SUCCESS: 'PERFORMERS_LOAD_SUCCESS',
    LOAD_FAILED: 'PERFORMERS_LOAD_FAILED',
};

const PERFORMERALBUMS = {
    LOAD: 'PERFORMERALBUMS_LOAD',
    LOAD_SUCCESS: 'PERFORMERALBUMS_LOAD_SUCCESS',
    LOAD_FAILED: 'PERFORMERALBUMS_LOAD_FAILED',
};

const PERFORMERIMAGES = {
    LOAD: 'PERFORMERIMAGES_LOAD',
    LOAD_SUCCESS: 'PERFORMERIMAGES_LOAD_SUCCESS',
    LOAD_FAILED: 'PERFORMERIMAGES_LOAD_FAILED',
};

const PERFORMERVIDEOS = {
    LOAD: 'PERFORMERVIDEOS_LOAD',
    LOAD_SUCCESS: 'PERFORMERVIDEOS_LOAD_SUCCESS',
    LOAD_FAILED: 'PERFORMERVIDEOS_LOAD_FAILED',
};

export {PERFORMERS, PERFORMERALBUMS, PERFORMERIMAGES, PERFORMERVIDEOS};